site_name: ITS - Ontology - Time
site_description: A registry for documenting the ontology of time concepts for use
  within ITS
repo_url: https://github.com/k-vaughn/ontology-its-time
nav:
- Home: index.md
- Core Pattern:
  - Core Pattern Overview: classes/CorePattern.md
  - Classes:
    - Time Thing: classes/TimeThing.md
  - Properties:
    - TimeDataProperty: properties/TimeDataProperty.md
    - TimeObjectProperty: properties/TimeObjectProperty.md
- Fuzzy Time Pattern:
  - Fuzzy Time Pattern Overview: classes/FuzzyTimePattern.md
  - Classes:
    - Clock Time: classes/ClockTime.md
    - Fuzzy Time Instant: classes/FuzzyTimeInstant.md
    - Fuzzy Time Instant Code: classes/FuzzyTimeInstantCode.md
    - Fuzzy Time Period: classes/FuzzyTimePeriod.md
    - Time Of Day: classes/TimeOfDay.md
  - Properties:
    - offset: properties/offset.md
    - timeReference: properties/timeReference.md
- Schedule Pattern:
  - Schedule Pattern Overview: classes/SchedulePattern.md
  - Classes:
    - Calendar Week Within Month: classes/CalendarWeekWithinMonth.md
    - Date Within Month: classes/DateWithinMonth.md
    - Day Week Month: classes/DayWeekMonth.md
    - Instance Of Day Within Month: classes/InstanceOfDayWithinMonth.md
    - Overall Period: classes/OverallPeriod.md
    - Period: classes/Period.md
    - Public Event Code: classes/PublicEventCode.md
    - Public Holiday: classes/PublicHoliday.md
    - Schedule: classes/Schedule.md
    - Schedule Thing: classes/ScheduleThing.md
    - Special Day: classes/SpecialDay.md
    - Special Day Type Code: classes/SpecialDayTypeCode.md
    - Time Period Of Day: classes/TimePeriodOfDay.md
    - Validity Status Code: classes/ValidityStatusCode.md
    - Week Code: classes/WeekCode.md
  - Properties:
    - applicableArea: properties/applicableArea.md
    - applicableDayOfWeek: properties/applicableDayOfWeek.md
    - applicableInstanceOfDayWithinMonth: properties/applicableInstanceOfDayWithinMonth.md
    - applicableMonth: properties/applicableMonth.md
    - applicableWeek: properties/applicableWeek.md
    - dailyEndTime: properties/dailyEndTime.md
    - dailyStartTime: properties/dailyStartTime.md
    - endOfPeriod: properties/endOfPeriod.md
    - exceptionPeriod: properties/exceptionPeriod.md
    - hasApplicableFuzzyTimePeriod: properties/hasApplicableFuzzyTimePeriod.md
    - hasPublicEventType: properties/hasPublicEventType.md
    - hasRecurringDayWeekMonthPeriod: properties/hasRecurringDayWeekMonthPeriod.md
    - hasRecurringSpecialDay: properties/hasRecurringSpecialDay.md
    - hasRecurringTimePeriodOfDay: properties/hasRecurringTimePeriodOfDay.md
    - hasSpecialDayType: properties/hasSpecialDayType.md
    - hasValidityStatus: properties/hasValidityStatus.md
    - intersectWithApplicableDays: properties/intersectWithApplicableDays.md
    - isOverrunning: properties/isOverrunning.md
    - overallEndTime: properties/overallEndTime.md
    - overallStartTime: properties/overallStartTime.md
    - reverseInstance: properties/reverseInstance.md
    - ScheduleDataProperty: properties/ScheduleDataProperty.md
    - ScheduleObjectProperty: properties/ScheduleObjectProperty.md
    - startOfPeriod: properties/startOfPeriod.md
    - validityTimeSpecification: properties/validityTimeSpecification.md
    - validPeriod: properties/validPeriod.md
site_url: https://github.com/k-vaughn/ontology-its-time
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
  <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank"
  rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
  alt=""></a></p>
theme:
  name: material
  features:
  - content.code.copy
  - content.status
  - content.tooltips
  - icons
  - navigation.path
  - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
plugins:
- search
- git-revision-date-localized:
    type: date
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- md_in_html
- meta
- footnotes
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: docs
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: ''
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
extra:
  search:
    highlight: true
  hide:
  - title
  version:
    provider: mike
    alias: true
    default: latest
