name: Label issues with "triage needed"

on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label new issue with "triage needed"
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.payload.issue.number;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: ['triage needed']
            });